name: Hello #ワークフロー名
on: push #イベント(プッシュ時に起動)
jobs: #ジョブの定義
  hello: #ジョブID
    runs-on: ubuntu-latest #ランナー(Ubuntuで実行)
    steps:
      -run: echo "Hello, World!" #shellCommandの呼び出し
      -uses: actions/checkout@v4 #アクションの呼び出し